### ISSUE TITLE
Some existing packages that could be used?

### ISSUE THREAD

**Issue by tombisho** [FlorianSchw/dsIntestinalMicrobiomicsClient#1]
Hi Florian, I was interested to hear you were looking at microbiome data. I wondered if you had investigated some of the existing packages that are out there to avoid possible duplication?

For example, in the dsOmics package, there are functions for doing [differential gene expression analysis](https://isglobal-brge.github.io/resource_bookdown/differential-gene-expression-dge-analysis.html), which I believe are also relevant to microbiome analysis.

There is also an existing [dsMicrobiome package](https://github.com/StuartWheater/dsMicrobiomeClient) which has more of a focus on some of the ecological functions.

 Even if the functions that are required for your project aren't in these packages, perhaps it might help to add them instead of creating more packages?

I hope that some of this might be useful!

Tom

**Comment by FlorianSchw** [comment]
Hi Tom,
yes, I have been looking at the existing packages beforehand. Also my colleagues from the MDC, who are leading the INTIMIC project, tried out existing DataSHIELD packages on their data. The main issue that they have is zero-inflation of microbiome data. And there was no apparent solution to it yet. That's why they searched for alternatives from native R functions. I have talked to Stuart about the dsMicrobiome package and he said it is not really in a finished shape. Of course, it is a good idea to merge the functions into a larger microbiome package (I guess, there might be more microbiome-related functions necessary in the future) once they are ready.

Best,
Florian

**Comment by tombisho** [comment]
Ok that's great - I just wanted to make sure there wasn't overlap
